# Generated by Django 5.1.4 on 2025-03-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="problems",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lessons.problem"
            ),
        ),
    ]
