version: '3'
services:
  # PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: asadbek20020107
      POSTGRES_USER: asadbek20020107
      POSTGRES_PASSWORD: asadbek20020107
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Redis
  redis:
    image: redis:latest
    networks:
      - app_network

  # Django web server
  web:
    build: ./app/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network
    environment:
      DJANGO_ENV: development  # Bu yerda `development` yoki `production` muhitini tanlashingiz mumkin

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
