# Generated by Django 5.1.4 on 2025-01-14 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_problem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_data',
            field=models.CharField(default=datetime.datetime(2025, 1, 14, 20, 15, 55, 770267, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.CharField(max_length=200),
        ),
    ]
