# Generated by Django 5.1.4 on 2025-01-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_testcase_expected_output_testcase_output_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('darslik', 'darslik'), ('probelm', 'probelm')], max_length=50),
        ),
    ]
