# Generated by Django 5.1.4 on 2025-01-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='problem',
            new_name='algorithm',
        ),
    ]
