# Generated by Django 5.1.4 on 2025-01-31 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savollar', '0001_initial'),
        ('solution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userquestionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savollar.question'),
        ),
        migrations.AddField(
            model_name='userquestionresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userquizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savollar.quiz'),
        ),
        migrations.AddField(
            model_name='userquizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('user', 'problem', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='userquestionresult',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='userquizresult',
            unique_together={('user', 'quiz')},
        ),
    ]
