# Generated by Django 5.1.4 on 2025-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solution", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="userquestionresult",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="userquizresult",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
