# Generated by Django 5.1.4 on 2025-02-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTrue',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('solution.userquestionresult',),
        ),
    ]
