# Generated by Django 5.1.4 on 2025-02-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set(),
        ),
    ]
