# Generated by Django 5.1.4 on 2025-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_base_url', models.URLField(default='https://yourwebsite.com/certificate/')),
            ],
            options={
                'verbose_name': 'Sayt Sozlamasi',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
