# Generated by Django 5.1.4 on 2025-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_organization_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
