# Generated by Django 5.1.4 on 2025-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Certificate", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
