# Generated by Django 5.1.4 on 2025-02-23 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('r', 'Read'), ('w', 'Write'), ('c', 'Create'), ('d', 'Delete')], max_length=1, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_group_user_permission',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('group', 'user', 'resource', 'comment')},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_type',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_type',
            field=models.ManyToManyField(related_name='user_permissions', to='grade.permissiontype'),
        ),
    ]
