# Generated by Django 5.1.4 on 2025-03-19 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="unlisted",
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="mymodules",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["created_at", "updated_at", "is_active"],
                name="courses_cou_created_fef55c_idx",
            ),
        ),
    ]
