# Generated by Django 5.1.4 on 2025-03-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
    ]
