# Generated by Django 5.1.4 on 2025-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_at',
        ),
    ]
