# Generated by Django 5.1.4 on 2025-02-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerTrue',
        ),
    ]
