# Generated by Django 5.1.4 on 2025-01-20 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('savollar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savol',
            name='problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.problem'),
        ),
        migrations.AddField(
            model_name='results',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='savollar.savol'),
        ),
        migrations.AddField(
            model_name='varyant',
            name='savol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savollar.savol'),
        ),
    ]
