# Generated by Django 5.1.4 on 2025-03-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savollar", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="MyModules",
            new_name="modules",
        ),
    ]
