# Generated by Django 5.1.4 on 2025-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0003_category_question_answer_quiz_topic_useranswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
