# Generated by Django 5.1.4 on 2025-01-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0004_alter_question_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
