# Generated by Django 5.1.4 on 2025-02-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('userstatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonstatus',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_status', to='lessons.lesson'),
        ),
    ]
